version: '3.8'

services:
  ebarimt:
    image: munkhaltai/ebarimt:latest
    restart: always
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - ./libPosAPI.so:/home/ebarimtuser/app/libPosAPI.so #./libPosAPI.so path your so file
      - ./ebarimt_data:/home/ebarimtuser/.vatps:rw
    environment:
      - TZ=Asia/Ulaanbaatar

